name: Deploy Workflow

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Template
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.rest.actions.createWorkflowDispatch({
              owner: 'Ludvigpbf',
              repo: 'deploy-template',
              ref: 'deploy',
              workflow_id: 'deploy.yml',
              inputs: {
                'repo-name': process.env.GITHUB_REPOSITORY,
                'server': process.env.SERVER,
                'username': process.env.USERNAME,
                'password': process.env.PASS
              }
            });
            console.log('Workflow dispatch response:', data);
          github-token: ${{ secrets.ACCESS_TOKEN }}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
          PASS: ${{ secrets.PASS }}