name: Deploy Workflow

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Template
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.rest.actions.createWorkflowDispatch({
              owner: 'Ludvigpbf',
              repo: 'deploy-template',
              ref: 'deploy',
              workflow_id: 'deploy.yml',
              inputs: {
                'repo-name': `${github.context.repo.owner}/${github.context.repo.repo}`
              }
            });
            console.log('Workflow dispatch response:', data);
          github-token: ${{ secrets.ACCESS_TOKEN }}